### ISSUE TITLE
Week 5 - Milestone

### ISSUE THREAD

**Issue by phu0n9** [mnskgrayce/real-estate-mgt#1]
**Back-end:**
Creating _boilerplate:_
- [x] House, Rental @0xMYsteRy 
- [x] Meeting, Deposit @phu0n9 
- [x] Users, Renter, HouseMate @mnskgrayce 

Merge code on Tuesday week 6
